// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: jobs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getOverduePendingJobsFromTime = `-- name: GetOverduePendingJobsFromTime :many
SELECT id, name, arguments, run_at
FROM jobs
WHERE run_at <= ?1 AND status = 'pending'
`

type GetOverduePendingJobsFromTimeRow struct {
	ID        string
	Name      string
	Arguments string
	RunAt     int64
}

func (q *Queries) GetOverduePendingJobsFromTime(ctx context.Context, from int64) ([]GetOverduePendingJobsFromTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, getOverduePendingJobsFromTime, from)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverduePendingJobsFromTimeRow
	for rows.Next() {
		var i GetOverduePendingJobsFromTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Arguments,
			&i.RunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleNewJob = `-- name: ScheduleNewJob :exec
INSERT INTO jobs (id, name, run_at, arguments)
VALUES (?, ?, ?, ?)
`

type ScheduleNewJobParams struct {
	ID        string
	Name      string
	RunAt     int64
	Arguments string
}

func (q *Queries) ScheduleNewJob(ctx context.Context, arg ScheduleNewJobParams) error {
	_, err := q.db.ExecContext(ctx, scheduleNewJob,
		arg.ID,
		arg.Name,
		arg.RunAt,
		arg.Arguments,
	)
	return err
}

const setFailedJob = `-- name: SetFailedJob :exec
UPDATE jobs
SET finished_at = strftime('%s', 'now'), failed_message = ?, status = 'failed'
WHERE id = ?
`

type SetFailedJobParams struct {
	FailedMessage sql.NullString
	ID            string
}

func (q *Queries) SetFailedJob(ctx context.Context, arg SetFailedJobParams) error {
	_, err := q.db.ExecContext(ctx, setFailedJob, arg.FailedMessage, arg.ID)
	return err
}

const setJobStatusToRunning = `-- name: SetJobStatusToRunning :exec
UPDATE jobs
SET status = 'running'
WHERE id = ?
`

func (q *Queries) SetJobStatusToRunning(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setJobStatusToRunning, id)
	return err
}

const setSuccessfulJob = `-- name: SetSuccessfulJob :exec
UPDATE jobs
SET finished_at = strftime('%s', 'now'), status = 'success'
WHERE id = ?
`

func (q *Queries) SetSuccessfulJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setSuccessfulJob, id)
	return err
}
