// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package sqlc

import (
	"database/sql"
)

type Job struct {
	ID            string
	Name          string
	Status        string
	RunAt         int64
	Arguments     string
	FinishedAt    sql.NullInt64
	FailedMessage sql.NullString
	CreatedAt     int64
}

type Todo struct {
	ID        string
	Task      string
	Status    string
	CreatedAt int64
}

type TodosSearch struct {
	ID   string
	Task string
}

type TodosSearchConfig struct {
	K interface{}
	V interface{}
}

type TodosSearchContent struct {
	ID int64
	C0 interface{}
	C1 interface{}
}

type TodosSearchData struct {
	ID    int64
	Block []byte
}

type TodosSearchDocsize struct {
	ID int64
	Sz []byte
}

type TodosSearchIdx struct {
	Segid interface{}
	Term  interface{}
	Pgno  interface{}
}
