// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :execresult
INSERT INTO todos (id, task, status)
VALUES (?, ?, ?)
`

type CreateTodoParams struct {
	ID     string
	Task   string
	Status string
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTodo, arg.ID, arg.Task, arg.Status)
}

const getTodo = `-- name: GetTodo :one
SELECT id, task, status, created_at
FROM todos
WHERE id = ?
`

func (q *Queries) GetTodo(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTodos = `-- name: GetTodos :many
SELECT id, task, status, created_at
FROM todos
ORDER BY created_at DESC
`

func (q *Queries) GetTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTodoStatus = `-- name: SetTodoStatus :execresult
UPDATE todos
SET status = ?
WHERE id = ?
`

type SetTodoStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetTodoStatus(ctx context.Context, arg SetTodoStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setTodoStatus, arg.Status, arg.ID)
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET task   = ?,
    status = ?
WHERE id = ?
RETURNING id, task, status, created_at
`

type UpdateTodoParams struct {
	Task   string
	Status string
	ID     string
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo, arg.Task, arg.Status, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
