name: Go

on: [push, pull_request]

permissions:
  deployments: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Tools
      run: make tools

    - name: Lint
      run: make lint

    - name: Bench
      run: make bench