name: Go

on: [push, pull_request]

permissions:
  deployments: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Tools
      run: make tools

    - name: Lint
      run: make lint

    - name: Bench
      run: make bench

#    - name: Download previous benchmark data
#      uses: actions/cache@v1
#      with:
#        path: ./cache
#        key: ${{ runner.os }}-benchmark
#
#    - name: Store benchmark result
#      uses: benchmark-action/github-action-benchmark@v1
#      with:
#        tool: 'go'
#        output-file-path: bin/bench.txt
#        external-data-json-path: ./cache/bench.txt
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        auto-push: true
#        fail-on-alert: true
#        alert-threshold: '200%'
#        comment-on-alert: true
#        alert-comment-cc-users: '@roscrl'